---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

# https://eslint.org/docs/user-guide/configuring#specifying-environments
extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0